### ISSUE TITLE
Error compiling the project

### ISSUE THREAD

**Issue by qmatteoq** [jamesmcroft/MicrosoftBand-BackgroundSample#1]
Hello, I'm trying to compile the project on my PC (Windows 10 + Visual Studio 2015) but I always get the following errors:

3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1994,5): error APPX0702: Payload file 'C:\Users\mpagani\Desktop\MicrosoftBand-BackgroundSample-master\Band.BackgroundSample\packages\Microsoft.Band.1.3.10702\lib\portable-win81+wpa81\Microsoft.Band.Store\Microsoft.Band.Store.xr.xml' does not exist.
3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1994,5): error APPX0702: Payload file 'C:\Users\mpagani\Desktop\MicrosoftBand-BackgroundSample-master\Band.BackgroundSample\packages\Microsoft.Band.1.3.10702\lib\portable-win81+wpa81\Microsoft.Band.Store\Sensors\SensorConsentPage.xbf' does not exist.
3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1994,5): error APPX0702: Payload file 'C:\Users\mpagani\Desktop\MicrosoftBand-BackgroundSample-master\Band.BackgroundSample\packages\Microsoft.Band.1.3.10702\lib\portable-win81+wpa81\Microsoft.Band.Store\Tiles\AddTilePage.xbf' does not exist.

I've tried to upgrade the Band SDK, but nothing changed.

**Comment by RumRogers** [comment]
Same here!

**Comment by jamesmcroft** [comment]
I'll have a look into it. I built the demo in VS2015 Windows 10 for Windows Phone 8.1 so unless you haven't got the Windows 8.1 / Phone SDKs installed with your version of VS? I'll have a play around, see if I can see what's happening.

**Comment by jamesmcroft** [comment]
So unfortunately, this isn't a problem with this project. It's actually an issue with the current state of the SDK and how the references work with the background task project as it requires the reference to the Band.Phone and Band.Store libraries to connect but those also reference UI element which obviously aren't supported by the background task project. The only solution is to copy the two folders from the wpa81 lib folder (Microsoft.Band.Phone & Microsoft.Band.Store) into the location that it is erroring on when you're attempting to build the project.

**Comment by RumRogers** [comment]
Yes, that's exactly how I managed to compile the project some weeks ago.
Thanks anyway and keep up the great work!
